# Generated by Django 4.2.23 on 2025-07-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('species_applicable', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
